name: Python package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      
      - name: Test with pytest
        run: python -m pytest pytests.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
